# Generated by Django 5.2.7 on 2025-10-08 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField(blank=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает принятия'), ('ACCEPTED', 'Принят водителем'), ('IN_PROGRESS', 'В пути'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменен')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_driver_sharing_location', models.BooleanField(default=False)),
                ('cargo_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo.cargotype')),
                ('departure_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_orders', to='locations.location')),
                ('destination_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_orders', to='locations.location')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_orders', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(limit_choices_to={'role': 'SENDER'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='cargo_order_status_292ce1_idx'), models.Index(fields=['sender', 'created_at'], name='cargo_order_sender__c39d0f_idx')],
            },
        ),
    ]
