# Generated by Django 5.2.7 on 2025-10-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'Tariff Settings',
            },
        ),
    ]
